name: easy_udp
description: >
  This library provides a wrapper over RawDatagramSocket
  to gracefully handle UDP connections in dartlang. ðŸ˜†
version: 1.2.0
homepage: https://github.com//xtyxtyx/easy_udp
author: xuty <xty50337@hotmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  async: ^2.3.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
